---
layout: post
title: "[Javascript] 자바스크립트 Promise(2)"
data: '2021-12-25'
category: ['Javascript']

---

코드를 작성한대로 출력되는것을 동기방식이라고 한다. 

setTimeout을 사용하면 코드를 작성한대로가아닌 setTimout이 끝나서야 코드가 출력된다. 

setTimout을 사용할때 순서대로 출력이 되길원하면 callback 함수를 사용한다. 
```js
function a(callback) {
  //A가 실행된뒤에 callback함수를 통해 B를 실행한다. 
  setTimeout(() => {
    console.log('A')
    callback()//인수로 받은 함수를 실행
    // b()실행
  }, 1000)
}
function b() {
  console.log('B')
}
a(function() {
  b()//콜백함수
})
```
함수 내에서 callback()이실행되기때문에 콜백을 받는 함수는 인수로 function을 만들어줘야한다. callback()있는데 호추함수 인수가 비어있는상태에서 호출하면 오류발생 한다.

콜백지옥
```js
a(function () {
  b(function () {
    c(function() {
      d(function() {
        console.log('done!')
      })
    })
  })
})
```

## Promis 생성자 함수
```js
function a() {
  // pomise: 약속의 객체!
  return new Promise(function (resolve){
    setTimeout(function() {
      console.log('A')
      resolve('Hello A')
      //resolve가 실행되고나서 b()가 실행된다. 
    }, 1000)
  })
}
function b() {
  console.log('B')
}
async function test() {
  const res = await a()//await => a()가 실행일 끝날때까지 기다려라 
  console.log('res', res)
  //function a에서 resolve가 실행되면서 인수로 준 Hello A가 res에 담겨서 출력된다.
  b()
}

test()
```
만약 a와같이 Promise를 사용한 b,c,d가 있다면 다음과 같이 부를수 있다. 
```js
async function test() {
  const h1 =await a()
  const h2 = await b()
  const h3 = await c()
  const h4 = await d()
  //A B C D
  console.log('Done!')  //Done!
  console.log(h1, h2, h3, h4) //Hello A Hello B Hello C Hello D
}
```
async/await를 사용할수 없을때 then을 사용하여 실행할 수 있다.
```js
function test() { 
  a ()
  .then(()=>b())
  .then(()=>c())
  .then(()=>d())
  .then(()=>{
    console.log('Done!')
  })
}
```
## 예외처리
```js
function a(number) {
  return new Promise((resolve, reject)
  //resolve는 이행완료됐을때
  //reject는 정상적으로 실행되지않았을때 호출
   => {
    if(number > 4){
      reject()
      return
    }
    setTimeout(() => {
      console.log('A')
      resolve()
    }, 1000)
  })
}
function test() {
  a(7)
    .then(()=>{
      console.log('Resolve!')
    })
    .catch(()=>{
      console.log('Reject!')
      //reject으로 예외처리할때
    })
    .finally(()=>{
      //실행이 끝나면 실행
      console.log('Finally!')
    })
} 

test()
```
async/ await로 예외처리
```js
async function test() {
  try{
    await a()
    console.log('Resolve')
  } catch (error) {
    console.log('Reject!')
  } finally {
    console.log('Done!')
  }
} 
```
## 비동기 연습 

### API불러오기
```js
function fetchMovies(title) {
  const OMDB_API_KEY = '7035c60c'
  return new Promise (async (resolve, reject) => {
    const res = await axios.get (`https://www.omdbapi.com/?apikey=${OMDB_API_KEY}&s=${title}`)
    // console.log(res)
    resolve(res)
  })
}

async function test(){
  const res = await fetchMovies('frozen')
  //promise가 return 되었기 때문d에 async await를 사용할 수 있다.
  console.log(res)
}
//이렇게  fetchMovies function내부가아닌 test()를 통해 데이터를 부를수 있다.
//굳이 이렇게 따로 함수를 만들어서 부르는 것은 Promise안의 코드는 직관적이지 않고 확인하기 어렵다. 또한 API키를 노출하지 않을수 있다.  이렇게 따로 호출해서 사용하면 언제든 재활용이 가능하다. 
```
### 예외처리
```js
function fetchMovies(title) {
  // 대기(pending) : 이행사거나 거부되지 않은 초기 상태.
  const OMDB_API_KEY = '7035c60c123'//잘못된 key //인증이 유효하지않다 401 error
  return new Promise (async (resolve, reject) => {
   try{
    const res = await axios.get (`https://www.omdbapi.com/?apikey=${OMDB_API_KEY}&s=${title}`)
    // 이행(fulfilled) : 연산이 성공적으로 완료됨.
    resolve(res)
   } catch(error){
     console.log(error.message)
     // 거부(rejected) : 연산이 실패함.
     reject('error.message')
   }
  })
}

async function test(){
  try{
    const res = await fetchMovies('frozen')
    console.log(res)
  } catch (error) {
    console.log('error.message')
    
  }
}
test()
async function hello(){
  fetchMovies('jobs')
    .then(res => console.log(res))
    .catch(error => {console.log('error.message')})
}
hello()
```